# This is a basic workflow to help you get started with Actions

name: Update Activities

# Controls when the workflow will run
on:
   schedule:
      - cron: "30 * * * *"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest GitHub activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: activity - Readme
        uses: YoussefAMKamal/YoussefAMKamal@main
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
